### ISSUE TITLE
RuntimeError: CUDA error: no kernel image is available for execution on the device

### ISSUE THREAD

**Issue by GoroYeh-HRI** [eric-yyjau/pytorch-superpoint#118]
Hi, thank you for the great work!
I got this error when training the MagicPoint:
RuntimeError: CUDA error: no kernel image is available for execution on the device
![image](https://github.com/user-attachments/assets/b1a06bc5-4795-4e98-8e43-27cbe7c4cd1b)

Do you know what might be the issue? Thank you

**Comment by GoroYeh-HRI** [comment]
For some reason the problem was solved by running the following command:
`export CUDA_VISIBLE_DEVICES=1`

**Comment by Alexander8848** [comment]
i have the same problem, have you solved this problem?

**Comment by Alexander8848** [comment]
> For some reason the problem was solved by running the following command: `export CUDA_VISIBLE_DEVICES=1`

I do this ,but i don't save this problem,and you?
